In [1]:
# Step 1: Import our tools
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

print("✅ Libraries imported successfully!")

✅ Libraries imported successfully!

In [2]:
df = pd.read_csv(r'C:\Users\apurv\Documents\DataAnalystProjects\data\Sample - Superstore.csv', encoding='latin1')

print("Data loaded successfully!")
print("Total rows:", df.shape[0])
print("Total columns:", df.shape[1])

Data loaded successfully!
Total rows: 9994
Total columns: 21

In [3]:
df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,6/12/2016,6/16/2016,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164

In [4]:
df = pd.read_csv(r'C:\Users\apurv\Documents\DataAnalystProjects\data\Sample - Superstore.csv', encoding='latin1')

print("Data loaded successfully!")
print("Total rows:", df.shape[0])
print("Total columns:", df.shape[1])

Data loaded successfully!
Total rows: 9994
Total columns: 21

In [5]:
# Step 4: See all column names
print("All columns in our dataset:")
for i, col in enumerate(df.columns):
    print(f"  {i+1}. {col}")

All columns in our dataset:
  1. Row ID
  2. Order ID
  3. Order Date
  4. Ship Date
  5. Ship Mode
  6. Customer ID
  7. Customer Name
  8. Segment
  9. Country
  10. City
  11. State
  12. Postal Code
  13. Region
  14. Product ID
  15. Category
  16. Sub-Category
  17. Product Name
  18. Sales
  19. Quantity
  20. Discount
  21. Profit

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         9994 non-null   int64
 1   Order ID       9994 non-null   object
 2   Order Date     9994 non-null   object
 3   Ship Date      9994 non-null   object
 4   Ship Mode      9994 non-null   object
 5   Customer ID    9994 non-null   object
 6   Customer Name  9994 non-null   object
 7   Segment        9994 non-null   object
 8   Country        9994 non-null   object
 9   City           9994 non-null   object
 10  State          9994 non-null   object
 11  Postal Code    9994 non-null   int64
 12  Region         9994 non-null   object
 13  Product ID     9994 non-null   object
 14  Category       9994 non-null   object
 15  Sub-Category   9994 non-null   object
 16  Product Name   9994 non-null   object
 17  Sales          9994 non-null   float64
 18  Quantity       9994 non-null   int64
 19  Discount       9994 non-null   float64
 20  Profit         9994 non-null   float64
dtypes: float64(3), int64(3), object(15)
memory usage: 1.6+ MB

In [7]:
# Variables store data
company_name = "Superstore"
total_orders = 9994
average_sale = 229.85
is_profitable = True

print("Company:", company_name)
print("Total Orders:", total_orders)
print("Average Sale: $", average_sale)
print("Profitable?", is_profitable)

Company: Superstore
Total Orders: 9994
Average Sale: $ 229.85
Profitable? True

In [8]:
print(type(company_name))
print(type(total_orders))
print(type(average_sale))
print(type(is_profitable))

<class 'str'>
<class 'int'>
<class 'float'>
<class 'bool'>

In [9]:

regions = ["East", "West", "Central", "South"]
sales = [100, 250, 430, 180, 95]

print("Regions:", regions)
print("Sales:", sales)
print("First region:", regions[0])     
print("Last region:", regions[-1])     
print("Total regions:", len(regions))

Regions: ['East', 'West', 'Central', 'South']
Sales: [100, 250, 430, 180, 95]
First region: East
Last region: South
Total regions: 4

In [10]:
sales = [100, 250, 430, 180, 95]

print("Total sales:", sum(sales))
print("Average sale:", sum(sales) / len(sales))
print("Highest sale:", max(sales))
print("lowest sale:", min(sales))

Total sales: 1055
Average sale: 211.0
Highest sale: 430
lowest sale: 95

In [11]:
profit = -500

if profit> 0:
    print("This order made a PROFIT")
elif profit == 0:
     print("This order broke even")
else:
    print("This order made a Loss")

This order made a Loss

In [12]:
sale_amount = 1500

if sale_amount >= 1000:
    category = "High Value"
elif sale_amount >= 500:
    category = "Medium Value"
else:
    category = "Low Value"

print(f"Sale of ${sale_amount} is: {category}")

Sale of $1500 is: High Value

In [13]:
region = "West"
profit = 800

if region == "West" and profit > 500:
    print("High performing West region order!")

if region == "East" or region == "West":
    print("This is a coastal region order")

High performing West region order!
This is a coastal region order

In [14]:
regions = ["East", "West", "Central", "South"]

for region in regions:
    print("Processing region:", region)

Processing region: East
Processing region: West
Processing region: Central
Processing region: South

In [15]:
sales = [100, 250, 430, 180, 95]
tax_rate = 0.18

print("Sales after 18% tax:")
for sale in sales:
    after_tax = sale * (1 + tax_rate)
    print(f"  Original: ${sale}  →  After tax: ${round(after_tax, 2)}")

Sales after 18% tax:
  Original: $100  →  After tax: $118.0
  Original: $250  →  After tax: $295.0
  Original: $430  →  After tax: $507.4
  Original: $180  →  After tax: $212.4
  Original: $95  →  After tax: $112.1

In [16]:
profits = [200, -150, 430, -80, 95, -300, 150]

print("Loss-making orders:")
for i, profit in enumerate(profits):
    if profit < 0:
        print(f"  Order {i+1}: Loss of ${abs(profit)}")

Loss-making orders:
  Order 2: Loss of $150
  Order 4: Loss of $80
  Order 6: Loss of $300

In [17]:
def calculate_profit_margin(sales, profit):
    margin = (profit / sales) * 100
    return round(margin, 2)

margin1 = calculate_profit_margin(500, 75)
margin2 = calculate_profit_margin(1200, 96)
margin3 = calculate_profit_margin(300, -45)

print(f"Order 1 margin: {margin1}%")
print(f"Order 2 margin: {margin2}%")
print(f"Order 3 margin: {margin3}%")

Order 1 margin: 15.0%
Order 2 margin: 8.0%
Order 3 margin: -15.0%

In [18]:
def classify_order(profit):
    if profit > 500:
        return "High Profit"
    elif profit > 0:
        return "Low Profit"
    elif profit == 0:
        return "Break Even"
    else:
        return "Loss"

# Test it
test_profits = [850, 120, 0, -200]
for p in test_profits:
    print(f"Profit ${p}: {classify_order(p)}")

Profit $850: High Profit
Profit $120: Low Profit
Profit $0: Break Even
Profit $-200: Loss

In [19]:
order = {
    "order_id": "CA-2017-152156",
    "customer": "John Smith",
    "region": "East",
    "sales": 261.96,
    "profit": 41.91
}

print("Order ID:", order["order_id"])
print("Customer:", order["customer"])
print("Sales:", order["sales"])
print("Profit:", order["profit"])

Order ID: CA-2017-152156
Customer: John Smith
Sales: 261.96
Profit: 41.91

In [20]:
region_sales = {
    "East": 678781,
    "West": 725457,
    "Central": 501239,
    "South": 391721
}

best_region = max(region_sales, key=region_sales.get)
print("Best performing region:", best_region)
print("Their sales: $", region_sales[best_region])


print("\nAll regions:")
for region, sales in region_sales.items():
    print(f"  {region}: ${sales:,}")

Best performing region: West
Their sales: $ 725457

All regions:
  East: $678,781
  West: $725,457
  Central: $501,239
  South: $391,721

In [21]:
import pandas as pd

df = pd.read_csv(r'C:\Users\apurv\Documents\DataAnalystProjects\data\Sample - Superstore.csv', encoding='latin1')
print("Data loaded! Shape:", df.shape)

Data loaded! Shape: (9994, 21)

In [22]:
total_rows = df.shape[0]
total_columns = df.shape[1]
total_sales = df['Sales'].sum()
total_profit = df['Profit'].sum()
avg_order_value = df['Sales'].mean()

print(f"Total Orders: {total_rows:,}")
print(f"Total Revenue: ${total_sales:,.2f}")
print(f"Total Profit: ${total_profit:,.2f}")
print(f"Average Order Value: ${avg_order_value:,.2f}")

Total Orders: 9,994
Total Revenue: $2,297,200.86
Total Profit: $286,397.02
Average Order Value: $229.86

In [23]:
regions = df['Region'].unique().tolist()
categories = df['Category'].unique().tolist()

print("Regions in dataset:", regions)
print("Categories in dataset:", categories)
print("Number of unique customers:", df['Customer Name'].nunique())

Regions in dataset: ['South', 'West', 'Central', 'East']
Categories in dataset: ['Furniture', 'Office Supplies', 'Technology']
Number of unique customers: 793

In [24]:
def analyze_column(column_name):
    col = df[column_name]
    print(f"Analysis of '{column_name}':")
    print(f"  Total:   ${col.sum():,.2f}")
    print(f"  Average: ${col.mean():,.2f}")
    print(f"  Highest: ${col.max():,.2f}")
    print(f"  Lowest:  ${col.min():,.2f}")
    print()

# Run on Sales and Profit
analyze_column('Sales')
analyze_column('Profit')

Analysis of 'Sales':
  Total:   $2,297,200.86
  Average: $229.86
  Highest: $22,638.48
  Lowest:  $0.44

Analysis of 'Profit':
  Total:   $286,397.02
  Average: $28.66
  Highest: $8,399.98
  Lowest:  $-6,599.98

In [25]:
print("Sales by Region:")
for region in df['Region'].unique():
    region_data = df[df['Region'] == region]
    total = region_data['Sales'].sum()
    print(f"  {region}: ${total:,.2f}")

Sales by Region:
  South: $391,721.91
  West: $725,457.82
  Central: $501,239.89
  East: $678,781.24

In [26]:
print("Category Profitability Report:")
for category in df['Category'].unique():
    cat_data = df[df['Category'] == category]
    profit = cat_data['Profit'].sum()
    sales = cat_data['Sales'].sum()
    margin = (profit / sales) * 100

    if margin > 15:
        status = "Excellent"
    elif margin > 10:
        status = "Good"
    elif margin > 0:
        status = "Low"
    else:
        status = "Loss Making"

    print(f"  {category}: {round(margin,1)}% margin → {status}")

Category Profitability Report:
  Furniture: 2.5% margin → Low
  Office Supplies: 17.0% margin → Excellent
  Technology: 17.4% margin → Excellent

In [27]:
import pandas as pd
import numpy as np

df = pd.read_csv(r'C:\Users\apurv\Documents\DataAnalystProjects\data\Sample - Superstore.csv', encoding='latin1')

print("Data loaded! Shape:", df.shape)
df.head()

Data loaded! Shape: (9994, 21)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,6/12/2016,6/16/2016,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164

In [28]:
sales_col = df['Sales']

print(type(sales_col))  
print(sales_col.head(5))

<class 'pandas.core.series.Series'>
0    261.9600
1    731.9400
2     14.6200
3    957.5775
4     22.3680
Name: Sales, dtype: float64

In [29]:

subset = df[['Customer Name', 'Region', 'Sales', 'Profit']]

print("Shape of subset:", subset.shape)
subset.head(10)

Shape of subset: (9994, 4)

     Customer Name Region     Sales    Profit
0      Claire Gute  South  261.9600   41.9136
1      Claire Gute  South  731.9400  219.5820
2  Darrin Van Huff   West   14.6200    6.8714
3   Sean O'Donnell  South  957.5775 -383.0310
4   Sean O'Donnell  South   22.3680    2.5164
5  Brosina Hoffman   West   48.8600   14.1694
6  Brosina Hoffman   West    7.2800    1.9656
7  Brosina Hoffman   West  907.1520   90.7152
8  Brosina Hoffman   West   18.5040    5.7825
9  Brosina Hoffman   West  114.9000   34.4700

In [30]:
number_cols = df.select_dtypes(include='number')
print("Number columns:", number_cols.columns.tolist())

text_cols = df.select_dtypes(include='object')
print("Text columns:", text_cols.columns.tolist())

Number columns: ['Row ID', 'Postal Code', 'Sales', 'Quantity', 'Discount', 'Profit']
Text columns: ['Order ID', 'Order Date', 'Ship Date', 'Ship Mode', 'Customer ID', 'Customer Name', 'Segment', 'Country', 'City', 'State', 'Region', 'Product ID', 'Category', 'Sub-Category', 'Product Name']

In [31]:
east_orders = df[df['Region'] == 'East']

print("Total orders in East:", len(east_orders))
print("East region sales: $", round(east_orders['Sales'].sum(), 2))

Total orders in East: 2848
East region sales: $ 678781.24

In [32]:
high_value = df[df['Sales'] > 1000]

print("High value orders:", len(high_value))
high_value[['Customer Name', 'Category', 'Sales', 'Profit']].head(10)

High value orders: 468

       Customer Name         Category     Sales     Profit
10   Brosina Hoffman        Furniture  1706.184    85.3092
24       Emily Burns        Furniture  1044.630   240.2649
27   Tracy Blumstein        Furniture  3083.430 -1665.0522
35         Gene Hale       Technology  1097.544   123.4737
54    Janet Molinari       Technology  1029.950   298.6855
67     Brendan Sweed  Office Supplies  1113.024   111.3024
149   Justin Ellison        Furniture  1951.840   585.5520
165     Becky Martin       Technology  8159.952 -1359.9920
167     Becky Martin        Furniture  1740.060   -24.8580
215  Victoria Wilson       Technology  1188.000  -950.4000

In [33]:

losses = df[df['Profit'] < 0]

print("Loss making orders:", len(losses))
print("That is", round(len(losses)/len(df)*100, 1), "% of all orders")
print("Total money lost: $", round(losses['Profit'].sum(), 2))

Loss making orders: 1871
That is 18.7 % of all orders
Total money lost: $ -156131.29

In [34]:

good_orders = df[(df['Sales'] > 500) & (df['Profit'] > 0)]
print("High sales + profitable orders:", len(good_orders))

tech_furniture = df[(df['Category'] == 'Furniture') | (df['Category'] == 'Technology')]
print("Furniture or Tech orders:", len(tech_furniture))

High sales + profitable orders: 883
Furniture or Tech orders: 3968

In [35]:
phone_orders = df[df['Product Name'].str.contains('Phone', case=False)]

print("Phone related orders:", len(phone_orders))
print("Total phone sales: $", round(phone_orders['Sales'].sum(), 2))
phone_orders[['Product Name', 'Sales', 'Profit']].head(5)

Phone related orders: 528
Total phone sales: $ 189188.11

                                         Product Name     Sales    Profit
7                      Mitel 5320 IP Phone VoIP phone   907.152   90.7152
11      Konftel 250 Conference phone - Charcoal black   911.424   68.3568
19                            Cisco SPA 501G IP Phone   213.480   16.0110
48  LF Elite 3D Dazzle Designer Hard Case Cover, L...    21.800    6.1040
54                   AT&T CL83451 4-Handset Telephone  1029.950  298.6855

In [36]:

top_sales = df.sort_values('Sales', ascending=False)

print("Top 10 highest sales orders:")
top_sales[['Customer Name', 'Product Name', 'Sales', 'Profit']].head(10)

Top 10 highest sales orders:

,Customer Name,Product Name,Sales,Profit
2697,Sean Miller,Cisco TelePresence System EX90 Videoconferenci...,22638.480,-1811.0784
6826,Tamara Chand,Canon imageCLASS 2200 Advanced Copier,17499.950,8399.9760
8153,Raymond Buch,Canon imageCLASS 2200 Advanced Copier,13999.960,6719.9808
2623,Tom Ashbrook,Canon imageCLASS 2200 Advanced Copier,11199.968,3919.9888
4190,Hunter Lopez,Canon imageCLASS 2200 Advanced Copier,10499.970,5039.9856
9039,Adrian Barton,GBC Ibimaster 500 Manual ProClick Binding System,9892.740,4946.3700
4098,Sanjit Chand,Ibico EPK-21 Electric Binding System,9449.950,4630.4755
4277,Bill Shonely,"3D Systems Cube Printer, 2nd Generation, Magenta",9099.930,2365.9818
8488,Sanjit Engle,HP Designjet T520 Inkjet Large Format Printer ...,8749.950,2799.9840
6425,Christopher Conant,Canon imageCLASS 2200 Advanced Copier,8399.976,1119.9968

In [37]:

sorted_df = df.sort_values(['Region', 'Sales'], ascending=[True, False])

sorted_df[['Region', 'Customer Name', 'Sales']].head(10)

       Region    Customer Name      Sales
6826  Central     Tamara Chand  17499.950
9039  Central    Adrian Barton   9892.740
4098  Central     Sanjit Chand   9449.950
165   Central     Becky Martin   8159.952
6520  Central      Andy Reiter   5443.960
8990  Central      Harry Marie   4899.930
6620  Central   Cathy Prescott   4164.050
5198  Central       Alex Avila   3930.072
7683  Central  Shirley Daniels   3812.970
5170  Central  Laura Armstrong   3504.900

In [38]:
print("TOP 5 MOST PROFITABLE ORDERS:")
top5 = df.nlargest(5, 'Profit')[['Customer Name', 'Product Name', 'Sales', 'Profit']]
print(top5.to_string())

print()


print("TOP 5 BIGGEST LOSS ORDERS:")
bottom5 = df.nsmallest(5, 'Profit')[['Customer Name', 'Product Name', 'Sales', 'Profit']]
print(bottom5.to_string())

TOP 5 MOST PROFITABLE ORDERS:
      Customer Name                                      Product Name     Sales     Profit
6826   Tamara Chand             Canon imageCLASS 2200 Advanced Copier  17499.95  8399.9760
8153   Raymond Buch             Canon imageCLASS 2200 Advanced Copier  13999.96  6719.9808
4190   Hunter Lopez             Canon imageCLASS 2200 Advanced Copier  10499.97  5039.9856
9039  Adrian Barton  GBC Ibimaster 500 Manual ProClick Binding System   9892.74  4946.3700
4098   Sanjit Chand              Ibico EPK-21 Electric Binding System   9449.95  4630.4755

TOP 5 BIGGEST LOSS ORDERS:
       Customer Name                               Product Name     Sales     Profit
7772   Cindy Stewart  Cubify CubeX 3D Printer Double Head Print  4499.985 -6599.9780
683   Grant Thornton  Cubify CubeX 3D Printer Triple Head Print  7999.980 -3839.9904
9774     Luke Foster  GBC DocuBind P400 Electric Binding System  2177.584 -3701.8928
3011  Sharelle Roach  Lexmark MX611dhe Monochrome Laser Printer  2549.985 -3399.9800
4991   Henry Goldwyn       Ibico EPK-21 Electric Binding System  1889.990 -2929.4845

In [39]:

region_sales = df.groupby('Region')['Sales'].sum()

print("Total Sales by Region:")
print(region_sales.sort_values(ascending=False))

Total Sales by Region:
Region
West       725457.8245
East       678781.2400
Central    501239.8908
South      391721.9050
Name: Sales, dtype: float64

In [40]:
category_stats = df.groupby('Category').agg(
    Total_Sales   = ('Sales', 'sum'),
    Total_Profit  = ('Profit', 'sum'),
    Total_Orders  = ('Order ID', 'count'),
    Avg_Sale      = ('Sales', 'mean')
).round(2)

print("Category Performance:")
print(category_stats)

Category Performance:
                 Total_Sales  Total_Profit  Total_Orders  Avg_Sale
Category
Furniture          741999.80      18451.27          2121    349.83
Office Supplies    719047.03     122490.80          6026    119.32
Technology         836154.03     145454.95          1847    452.71

In [41]:

region_category = df.groupby(['Region', 'Category'])['Sales'].sum().reset_index()
region_category = region_category.sort_values('Sales', ascending=False)

print("Sales by Region and Category:")
print(region_category.head(12).to_string())

Sales by Region and Category:
     Region         Category        Sales
5      East       Technology  264973.9810
9      West        Furniture  252612.7435
11     West       Technology  251991.8320
10     West  Office Supplies  220853.2490
3      East        Furniture  208291.2040
4      East  Office Supplies  205516.0550
2   Central       Technology  170416.3120
1   Central  Office Supplies  167026.4150
0   Central        Furniture  163797.1638
8     South       Technology  148771.9080
7     South  Office Supplies  125651.3130
6     South        Furniture  117298.6840

In [42]:
summary = df.groupby('Category').agg(
    Sales  = ('Sales', 'sum'),
    Profit = ('Profit', 'sum')
).round(2)


summary['Profit_Margin_%'] = ((summary['Profit'] / summary['Sales']) * 100).round(1)

print("Category Summary with Profit Margin:")
print(summary)

Category Summary with Profit Margin:
                     Sales     Profit  Profit_Margin_%
Category
Furniture        741999.80   18451.27              2.5
Office Supplies  719047.03  122490.80             17.0
Technology       836154.03  145454.95             17.4

In [43]:

df['Profit_Margin'] = ((df['Profit'] / df['Sales']) * 100).round(2)


df['Order_Size'] = pd.cut(
    df['Sales'],
    bins=[0, 100, 500, 1000, 100000],
    labels=['Small', 'Medium', 'Large', 'Very Large']
)


df['Year'] = pd.to_datetime(df['Order Date']).dt.year
df['Month'] = pd.to_datetime(df['Order Date']).dt.month_name()

df[['Sales', 'Profit', 'Profit_Margin', 'Order_Size', 'Year', 'Month']].head(10)

      Sales    Profit  Profit_Margin Order_Size  Year     Month
0  261.9600   41.9136          16.00     Medium  2016  November
1  731.9400  219.5820          30.00      Large  2016  November
2   14.6200    6.8714          47.00      Small  2016      June
3  957.5775 -383.0310         -40.00      Large  2015   October
4   22.3680    2.5164          11.25      Small  2015   October
5   48.8600   14.1694          29.00      Small  2014      June
6    7.2800    1.9656          27.00      Small  2014      June
7  907.1520   90.7152          10.00      Large  2014      June
8   18.5040    5.7825          31.25      Small  2014      June
9  114.9000   34.4700          30.00     Medium  2014      June

In [44]:

print("Orders per Region:")
print(df['Region'].value_counts())

print()

print("Orders per Category:")
print(df['Category'].value_counts())

print()

print("Orders per Segment:")
print(df['Segment'].value_counts())

Orders per Region:
Region
West       3203
East       2848
Central    2323
South      1620
Name: count, dtype: int64

Orders per Category:
Category
Office Supplies    6026
Furniture          2121
Technology         1847
Name: count, dtype: int64

Orders per Segment:
Segment
Consumer       5191
Corporate      3020
Home Office    1783
Name: count, dtype: int64

In [45]:
print("=" * 50)
print("   SUPERSTORE SALES ANALYSIS REPORT")
print("=" * 50)

print("\n1. OVERALL PERFORMANCE")
print(f"   Total Orders:  {len(df):,}")
print(f"   Total Revenue: ${df['Sales'].sum():,.2f}")
print(f"   Total Profit:  ${df['Profit'].sum():,.2f}")
print(f"   Overall Margin: {round(df['Profit'].sum()/df['Sales'].sum()*100, 1)}%")


print("\n2. BEST PERFORMING REGION")
best = df.groupby('Region')['Sales'].sum().idxmax()
best_sales = df.groupby('Region')['Sales'].sum().max()
print(f"   {best} with ${best_sales:,.2f} in sales")


print("\n3. MOST PROFITABLE CATEGORY")
best_cat = df.groupby('Category')['Profit'].sum().idxmax()
best_profit = df.groupby('Category')['Profit'].sum().max()
print(f"   {best_cat} with ${best_profit:,.2f} in profit")


losses = df[df['Profit'] < 0]
print("\n4. LOSS ANALYSIS")
print(f"   Loss-making orders: {len(losses):,} ({round(len(losses)/len(df)*100,1)}%)")
print(f"   Total losses: ${losses['Profit'].sum():,.2f}")


print("\n5. TOP CUSTOMER")
top_cust = df.groupby('Customer Name')['Sales'].sum().idxmax()
top_cust_sales = df.groupby('Customer Name')['Sales'].sum().max()
print(f"   {top_cust} with ${top_cust_sales:,.2f} in purchases")

print("\n" + "=" * 50)
print("   END OF REPORT")
print("=" * 50)

==================================================
   SUPERSTORE SALES ANALYSIS REPORT
==================================================

1. OVERALL PERFORMANCE
   Total Orders:  9,994
   Total Revenue: $2,297,200.86
   Total Profit:  $286,397.02
   Overall Margin: 12.5%

2. BEST PERFORMING REGION
   West with $725,457.82 in sales

3. MOST PROFITABLE CATEGORY
   Technology with $145,454.95 in profit

4. LOSS ANALYSIS
   Loss-making orders: 1,871 (18.7%)
   Total losses: $-156,131.29

5. TOP CUSTOMER
   Sean Miller with $25,043.05 in purchases

==================================================
   END OF REPORT
==================================================